### 1.无配置规则表

### 创建
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "userId": 1
}

### 查询
GET http://localhost:8080/order/get/1

###
POST http://localhost:8080/users/pageByIds
Content-Type: application/json

{
  "ids": [
    1,2,3,4,5,6,7,8,9,11,13
  ],
  "names": [
    ""
  ],
  "offset": 10,
  "limit": 10
}



###
POST http://localhost:8080/users/groupByIds
Content-Type: application/json

{
  "ids": [
    1,2,3,4,5,6,7,8,9,11,13
  ]

}

### 2.广播表测试

POST http://localhost:8080/city/create
Content-Type: application/json

{
  "cityName": "厦门"
}


### 3.分库分表测试

### 单个创建

POST http://localhost:8080/users/create
Content-Type: application/json

{
  "name": "name1"
}


### 批量创建

POST http://localhost:8080/users/batchCreate
Content-Type: application/json

[
  {
    "name": "name1"
  },
  {
    "name": "name2"
  }
]


