spring:
  profiles:
    active: sharding-base,config5

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: pers.sharding.dao.domain
  configuration:
    map-underscore-to-camel-case: true

