# 无配置表的情况下默认查询
# 如果某个表没有配置任何规则（分片、主从等），则查询只会走固定某个数据源。
# 至于要走哪个数据源，则是按照数据源配置的顺序去选择。
# 例如表user无任何规则，且数据源配置了ds0,ds1，则优先使用ds0，如果ds0不存在表user，则依次后推。
spring:
  shardingsphere:
    datasource:
      # 定义数据源
      names: ds0
    rules:
      sharding:
        default-database-strategy:
          none:
        default-table-strategy:
          none:
        broadcast-tables:
          - city
