# 禁用sharding
spring:
  shardingsphere:
    enabled: false
  datasource:
    url: jdbc:mysql://${mysql.url}:3306/sharding_0?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8
    username: root
    password: sunshine

